#!/bin/bash
currentDateTs=$(date -j -f "%Y-%m-%d" $1 "+%s")
endDateTs=$(date -j -f "%Y-%m-%d" $2 "+%s")
offset=7*86400

while [ "$currentDateTs" -le "$endDateTs" ]
do
  date=$(date -j -f "%s" $currentDateTs "+%Y-%m-%d")
  p1='java -Xmx6g -cp ./vishesh-async-1.0-jar-with-dependencies.jar -Dconfig=file:/opt/demotool/demotool.properties -Dpipeline.simulator.appPrefix=homeadvisor -Dpipeline.simulator.entityName=servicepro_week -Dpipeline.simulator.targetFilePath="/tmp/homeadvisor/wk_status_3'
  p3='_data.json" -Dpipeline.simulator.csvFilePath="/tmp/homeadvisor/wk_status_3'
  p5='_data.csv" -Dpipeline.simulator.conversionType="CSV" -Dpipeline.simulator.inputParams=" " -Dpipeline.simulator.count="1000000" -Dsupport.email=ritesh@simility.com com.kumbay.async.Main PipelineSimulationJob ""'


pall=$p1$date$p3$date$p5
echo $pall
echo sleep 5m
  currentDateTs=$(($currentDateTs+$offset))
done
